from admin.routes.home import *
from admin.routes.people import *
from admin.routes.movie import *
from admin.routes.series import *
from admin.routes.episode import *
from admin.routes.ratings import *
from admin.routes.genres import *
from admin.routes.principals import *
from admin.routes.professions import *
from admin.routes.user import *
from admin.routes.suggestion import *
